spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://test:test@ankitacluster.hzmeu.mongodb.net/test
      database: Shopping_Cart
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /order-service-swagger.html
  operationsSorter: method


jwtSecret: secret
jwtExpiration: 86400